### ISSUE TITLE
Mejorar la interfaz de  registro usuario

### ISSUE THREAD

**Issue by manprogrammnig** [manprogrammnig/GRUPO-2-TODOLIST-FINAL#2]
Mejorar en el programa la interfaz del usuario para obtener un mejor diseño utilizando las herramientas de html y css

**Comment by perfectoISEI** [comment]
Habiéndose culminado la mejora del interfaz de registros de usuarios, se da culminado.

**Comment by manprogrammnig** [comment]
YA PERFECTO LO VAMOS A REVISAR  EN UNA REUNION PARA VER MEJORAS
